### ISSUE TITLE
Tipsy vulnerable to race conditions in show/hide

### ISSUE THREAD

**Issue by ssokolow** [jaz303/tipsy#1]
Tipsy is vulnerable to flickering the tooltip and leaving it undisplayed if the user moves their mouse over the associated element, out, and then in again quickly as part of getting the pointer into place. (eg. Crossing over the element in question and then moving the pointer back into it)

All it takes is for the operation to complete before the animation finishes. I've left it unfixed on http://gbindex.ssokolow.com/?story=9 for now if you want to try it. (There's a tipsy popup on the "spoiler" pattern)

Changing tip.css(...).animate(...) to tip.stop().css(...).animate(...) in the show callback fixes the problem.

There's another bug with the same effect that happens if you do it REALLY fast, but you have to do it so quickly that it becomes almost impossible to trigger for any screen region small enough to merit a tipsy popup.

I've confirmed the bug as present in Google Chrome, Arora (another WebKit browser), and current Firefox.

**Comment by jaz303** [comment]
fixed race condition when fade is enabled (Closed by 5480fe7eb96d4a51ee818a51c0466e47c13448c8)
