### ISSUE TITLE
Superfluous slash breaks tipsy on IE 7 and 8 w/ jQuery 1.3.2

### ISSUE THREAD

**Issue by agross** [jaz303/tipsy#15]
I had issues with tipsy on IE 7 and and IE 8 not displaying tooltips. tipsy's outermost div was added, but not the .tipsy-arrow and .tipsy-inner, thus causing tooltips not to show up.

Line 98 contains a superfluous slash that caused the issue:

<pre>&lt;div class="tipsy-inner"***/***&gt;&lt;/div&gt;</pre>

http://github.com/jaz303/tipsy/blob/master/src/javascripts/jquery.tipsy.js#L98

**Comment by jaz303** [comment]
Removed superfluous slash (closed by 4b3e29fa044af7babee2f9872d4917eb1642f644)

**Comment by jaz303** [comment]
good catch, also superfluous slash is an awesome name for a geek band. can you play guitar?

**Comment by agross** [comment]
Sadly, as of today, I'm only able to listen to music ;)
