### ISSUE TITLE
Out of date project ?

### ISSUE THREAD

**Issue by alxlion** [jaz303/tipsy#158]
Hi,

With the multitude of pull request and the inactivity of the author to maintain Tipsy up to date, I wondered if the project is always maintained or not.

Thanks.

**Comment by MartinMartimeo** [comment]
I think the project is primary maintained by the various forks of this for example from Daniel O'Connor in https://github.com/CloCkWeRX/tipsy and I think in the idea and spirit lives maintained in the bootstrap tipsy and similiar.
