### ISSUE TITLE
Tipsy Won't Show Up in Facebox

### ISSUE THREAD

**Issue by chacha13** [jaz303/tipsy#16]
Hi. . . Your plugin kinda don't work on Facebox. . . Can u help me?

**Comment by jaz303** [comment]
Hi... your bug report kinda lacks detail... could you explain exactly what the problem is?

**Comment by chacha13** [comment]
When I tried to implement it inside the Facebox. . . The tooltip doesn't show. . . But when I tested it without the Facebox. It works. Can u help me sir?

**Comment by jaz303** [comment]
Is the Facebox content loading dynamically? If so, you should try using the `{live: true}` configuration option. Otherwise I'd need to see some code reproducing the issue.

**Comment by ankit** [comment]
There is a good chance that this might be due to a lower z-index value of tooltip. This commit should fix it - http://github.com/ankit/tipsy/commit/b66bca94c9aadc454cc85078ffa5baef6c19ca9d
