### ISSUE TITLE
Tipsy's "fade: true" hard-codes the final opacity to 0.8

### ISSUE THREAD

**Issue by ssokolow** [jaz303/tipsy#2]
After attempting to modify the final opacity for tipsy's popup to 1.0 and having no luck, I looked into the source and discovered it was hard-coding it.

I had to edit tipsy to get 1.0 opacity on my setup and this shouldn't be necessary for something reusable like a jQuery plugin.

**Comment by jaz303** [comment]
Good point, will add an opacity config option for v0.2.0

**Comment by jaz303** [comment]
Added opacity option for specifiying target opacity on fade (Closed by af929836181d415c69d8c7f37932408438abb94b)
