### ISSUE TITLE
When delayIn is set to a non-zero value, native tooltip is displayed

### ISSUE THREAD

**Issue by ankit** [jaz303/tipsy#20]
I set delayIn to 1000. The title of the element changes after the first initial call of fixTitle(), when tipsy() is initialized for the element. 

In this case the native tooltip is displayed, since fixTitle() is only called after a delay of 1000ms.

I have fixed this issue in this commit - http://github.com/ankit/tipsy/commit/cc3d7359936a628e9bf3f44be24a0bf68f1b5b58

Thanks!

**Comment by jaz303** [comment]
Thank you for this, I have merged it in.
