### ISSUE TITLE
Replacing native tooltips using live event tipsy doesn't work

### ISSUE THREAD

**Issue by zol** [jaz303/tipsy#26]
When I try:

$('[title]').tipsy({live: true});

Tipsy tooltips don't disappear. Anyone have a fix/workaround for this?

Using tipsy version 1.0.0a with jquery 1.4.2

**Comment by zol** [comment]
Actually, my bad you need to use: $('[title], [original-title]').tipsy({live: true}); as tipsy removes the title attribute and thus stops the live event working.

**Comment by renekorss** [comment]
Thank you for this. I had the same issue.
