### ISSUE TITLE
Tipsy is active if title empty

### ISSUE THREAD

**Issue by tordans** [jaz303/tipsy#4]
Currently tipsy shows an empty tip if the title is empty (like title="").
IMO it should only be active if there is a title != " " or ""

**Comment by jaz303** [comment]
i will look into this

**Comment by jaz303** [comment]
added docs test case demonstrating that tooltips do not appear when tooltip text is empty (closed by a4e12801d93dccad42a8d56d4de6ed2954368f93)

**Comment by tordans** [comment]
thanks, it looks like i had an old version, sorry!

**Comment by jaz303** [comment]
no i just fixed this today.

http://github.com/jaz303/tipsy/commit/460b2b23fe853d70b7f841df234662c679fe24f9

-J
