### ISSUE TITLE
kill() or a simple unbind() method.

### ISSUE THREAD

**Issue by m19c** [jaz303/tipsy#45]
Hi there,

in my use case i need to unbind the jQuery.tipsy() plugin or the hover effect who was setted up by tipsy(). The problem is the configuration in tipsy().

Please implement a simple unbind method:

jQuery('selector').tipsyUnbind();

Greets,
Marc

**Comment by luciuz** [comment]
Any thoughts, MrBoolean?

**Comment by Molkobain** [comment]
Have you tried something like jQuery('selector').off('tipsy'); to remove it ?

**Comment by seekshreyas** [comment]
@MrBoolean : I think you can use `disable/enable` methods in **tipsy**

``` javascript
jQuery(selector).tipsy('disable');
```

**Comment by shadowhand** [comment]
@seekshreyas disabling the tooltip is not the same as removing it. Ideally, tipsy would have something like `.tipsy('destroy')` that would unbind and remove the tooltip entirely.
