### ISSUE TITLE
Width option

### ISSUE THREAD

**Issue by serhatyolacan** [jaz303/tipsy#50]
Is it possible to set tooltip 'width' with js codes? I don't want to set tooltip width with css. I am using your tooltip for text and images. Sometimes i got big images. So pictures overflows tooltip. If i can set tooltip width with js i can select custom width's for custom class or id's. Thank you, for your great work... For example:

$('.text').tipsy({width: 200});
$('#image-1').tipsy({width: auto'});

**Comment by jaz303** [comment]
I think I'll add a `css` option, which will be passed directly to jQuery's `css()` method. So you'd do something like:

`$('.foo').tipsy({css: {width: 200}});`

How does that sound?

**Comment by serhatyolacan** [comment]
Oh its perfect. Sounds good. I think, your plugin is best. Smallest and useful. Thanks for effort... And i wanna say something about backgrounds. http://www.colorzilla.com/gradient-editor/ here we can define nice css backgrounds. I did and now looks better :) Anyways. Thank you again...

**Comment by jtheoof** [comment]
Ticket was closed but no commit was made? Latest commit on master was on April 23rd... How can I get this fix?

**Comment by KrunchMuffin** [comment]
I guess this never got added?
