### ISSUE TITLE
Allow custom CSS (class) to a specific tip

### ISSUE THREAD

**Issue by shawiz** [jaz303/tipsy#61]
It would be nice if tipsy takes an option to define custom css class/properties so I can make a customized tip for a special element.

For example:

$('#search-box').tipsy({className:'search-tip'});

in css:
.search-tip {
  padding: 3px 10px;
  font-size: 15px;
}

**Comment by jaz303** [comment]
This is in there:

https://github.com/jaz303/tipsy/commit/602f2fe5c3869bc2dcf8ea3737685f1bea294bc4

**Comment by shawiz** [comment]
Thank you. That was fast : )
