### ISSUE TITLE
Why the need to have Multiple ID's?

### ISSUE THREAD

**Issue by DejaVu** [jaz303/tipsy#63]
For the same thing?

I want all the Tips to Fade from the West. 
Adding the ID - west only makes the first one work. The rest are ignored. 

If the Element is a HTML Tag though - like Input - it will do the lot all the same.

**Comment by jaz303** [comment]
The examples use IDs because each targets only a single element. You could just as easily use classes:

```
$('.tooltip').tipsy({fade: true, gravity: 'w'});
```

**Comment by DejaVu** [comment]
I have a DIV already in place called .zoom that I would like to target, I am also targeting all INPUT tags. 

Using this Javascript does not seem to solve it. 
`<script type='text/javascript'>
    $(function() {
        $('input').tipsy({gravity: 'w', fade: true});
        $('.zoom').tipsy({gravity: 'n',fade: true});    
    });
</script>`

Inputs work, zoom classes are ignored. The DIV has an image hyperlink in it, yet they all have titles. 

What am I missing?
