### ISSUE TITLE
When a tooltipped object is deleted while the tooltip is shown, the tooltip never disappears (as there will be no mouseout event)

### ISSUE THREAD

**Issue by jaz303** [jaz303/tipsy#8]

**Comment by jaz303** [comment]
I've added a validate() method to the Tipsy object, which you can call by doing $('#element-to-be-deleted').tipsy('validate') - this will remove the tooltip if the tooltipped object is no longer in the DOM. I think this is the best that can be done without the ability to observe the DOM for changes.

**Comment by jaz303** [comment]
added validate() method for removing tipsy when tooltipped element is no longer in the DOM (closed by 102654858bdf17485a8e624b0ee0fcce2a91b44e)

**Comment by gkostov** [comment]
How is this method called? I was just going to fork the project and add the same code triggered by a timer while the tip is showing. I accidentally noticed this little function in the prototype but still I do not know if I can rely on it to automatically hide obsolete Tipsy objects. Can you please advise? Thanks
